<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [2]:
def greeting(name):
    if name == 'Batman':
        return 'Hellow Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

greeting('Superman')

'Hello Superman!'

In [3]:
def greeting(name):
    if name == 'Batman':
        return 'Hellow Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

greeting('Batman')

'Hellow Batman! So, nice to meet you!'

In [7]:
import numpy as np
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

basic_stats([1, 2, 3, 4, 5])

(1, 5, 3.0)

### 1.2 Named functions that don’t return

In [ ]:

# Your code here


### 1.3 Anonymous functions

In [10]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Super Man")

'Hello Super Man!'

In [16]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers, key=lambda x: x[1])  

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [17]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers, key=lambda x: sum(x))  

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [19]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting()

'Hello no one!'

## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [20]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

'return' terminates the function, hence there is no need for 'else' as the function has been stop when the 'if' function does not succeed

## Exercise 2 :  Calculator functions

In [10]:
def add(x,y):
    total = x + y
    return total

add(x=np.array([36, 34, 44, 76, 27]) , y=np.array([64, 66, 56, 24, 73]))
   

array([100, 100, 100, 100, 100])

In [11]:
def subtract(x,y):
    total = x - y
    return total

subtract(x=np.array([36, 34, 44, 76, 27]) , y=np.array([64, 66, 56, 24, 73]))
   

array([-28, -32, -12,  52, -46])

In [9]:
def multiply (x,y):
    total = x * y
    return total

multiply(x=np.array([36, 34, 44, 76, 27]) , y=np.array([64, 66, 56, 24, 73]))

array([2304, 2244, 2464, 1824, 1971])

In [8]:
def divide (x,y):
    if any(y == 0):
        print('exit')
        exit()
    else:
        total = x / y
        return total

divide(x=np.array([36, 34, 44, 76, 27]) , y=np.array([ 64, 66, 56, 24, 73]))

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 3 :  max_info() with NumPy

In [20]:
def max_info(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.max(), np_numbers.argmax()

list_max, list_argmax = max_info([40, 27, 83, 44, 74, 51, 76, 77, 10, 49])

print(list_max, list_argmax)

83 2
