<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [ ]:

# Your code here


### 1.2 Accessing data from a list (or array)

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])

Natasha Romanoff


In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_super_names[0])

Black Widow


### 1.3 Accessing data from a dictionary

In [6]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Tony Stark"])

Iron Man


### 1.4 Higher dimensional lists

In [9]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

print(superhero_info["Natasha Romanoff"])

Black Widow


## 2 Lists vs. Arrays

### 2.1 Size

In [13]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

len(py_list_2d)
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [ ]:

# Your code here


### 2.3 Adding a number

In [14]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [15]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [16]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [17]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array>3

array([False, False, False,  True,  True])

### 2.8 Mathematics

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

sum(py_list)

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

max(py_list)

5

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

min(py_list)

1

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array.sum()

15

In [26]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)   

np_array.mean()

3.0

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array.max()

5

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

np_array.min()

1

## Exercise 1 :  Total recall?

1. Both can be use to store data, perform functions like min, max and sum
2. Lists are unable to perform functions like squaring and adding a number, while an Array can. 
3. Dictionary can be use to store relationsip between data 



## Exercise 2 :  Index me

In [10]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

print(py_list[0],py_list[2],py_list[4],py_list[6],py_list[8])

a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [26]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

print(superhero_info["Tony Stark"])

IRON MAN


## Exercise 4 :  How many ones

In [2]:
py_list = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1, 99, 62, 86, 43, 42, 60, 59, 1, 1, 35, 83, 47, 34, 28, 68, 23, 22, 92, 1, 79, 1, 29, 94, 72, 46, 47, 1, 74, 32, 20, 8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
np_array=np.array(py_list)
(np_array == 1).sum()

9