<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list
x[5:2:-1]

['f6', 'e5', 'd4']

### 1.2 Subsetting by masking (Arrays only)

In [12]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [13]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[np_array>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[~(np_array>3)]

array([1, 2, 3])

In [16]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[(np_array>3)&(np_array<8)]

array([4, 5, 6, 7])

In [18]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[~(np_array<3)|(np_array>8)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [19]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3]

[4, 'D']

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3][0]

4

In [22]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[:5]

[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E']]

In [25]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[:5][1]

[2, 'B']

In [34]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[3:7][3]

[7, 'G']

### 1.4 Indexing & Slicing 2D Arrays

In [35]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[3] 

array(['4', 'D'], dtype='<U11')

In [36]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[3,0] 

'4'

In [37]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[:3] 

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [38]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[:3,0] 

array(['1', '2', '3'], dtype='<U11')

In [39]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[3:6,0] 

array(['4', '5', '6'], dtype='<U11')

In [41]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [42]:
x=[1]*10
x

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [43]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [44]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [45]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [47]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [49]:
a=(1, 2, 3)  
print(a[2])


3


### 2.2 Be VERY careful when copying

In [50]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

| Term       | Brief description                |   |
|------------|----------------------------------|---|
| Subsetting | To select                        |   |
| Indexing   | Selecting 1 element              |   |
| Slicing    | Selecting a range of elements    |   |
| Masking    | Only  true subset will show      |   |

## Exercise 2 :  Show me the ‘odd’ letters

In [19]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

let_np_array = np_array_2d[:10,0]
integ_np_array = let_np_array.astype(int)
integ_np_array % 2
mask = integ_np_array % 2 > 0
np_array_2d[mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')